"""Built-in demo ratings (no Streamlit import)."""

import pandas as pd


def build_sample_dataframe() -> pd.DataFrame:
    data = {
        "User": [
            "Alice",
            "Alice",
            "Alice",
            "Bob",
            "Bob",
            "Bob",
            "Charlie",
            "Charlie",
            "Charlie",
            "David",
            "David",
            "Eve",
            "Eve",
            "Eve",
            "Frank",
            "Frank",
            "Grace",
            "Grace",
            "Heidi",
            "Heidi",
            "Ivan",
            "Ivan",
            "Judy",
            "Judy",
            "Mallory",
            "Mallory",
            "Niaj",
            "Niaj",
            "Olivia",
            "Olivia",
            "Peggy",
            "Peggy",
            "Sybil",
            "Sybil",
            "Trent",
            "Trent",
            "Victor",
            "Victor",
            "Walter",
            "Walter",
        ],
        "Item": [
            "Elden Ring",
            "Halo",
            "Zelda",
            "Elden Ring",
            "Tetris",
            "COD",
            "Halo",
            "FIFA",
            "Minecraft",
            "COD",
            "FIFA",
            "Elden Ring",
            "Halo",
            "Zelda",
            "Halo",
            "Minecraft",
            "Zelda",
            "Mario Kart",
            "Elden Ring",
            "Mario Kart",
            "FIFA",
            "COD",
            "Zelda",
            "Mario Kart",
            "Tetris",
            "Minecraft",
            "Halo",
            "COD",
            "Elden Ring",
            "Zelda",
            "FIFA",
            "Mario Kart",
            "Tetris",
            "Halo",
            "Zelda",
            "COD",
            "Elden Ring",
            "FIFA",
            "Minecraft",
            "Mario Kart",
        ],
        "Rating": [
            5,
            4,
            5,
            5,
            3,
            2,
            4,
            5,
            4,
            4,
            5,
            5,
            5,
            4,
            4,
            5,
            5,
            5,
            5,
            4,
            2,
            3,
            4,
            5,
            3,
            4,
            4,
            5,
            5,
            5,
            2,
            5,
            3,
            4,
            5,
            2,
            5,
            4,
            5,
            5,
        ],
    }
    return pd.DataFrame(data)
